[package]
name = "thread-worker"
version = "0.1.0"
authors = ["Darius Wiles <github@dariuswiles.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.13"
